base_model: mistralai/Mistral-7B-v0.3
base_model_config: mistralai/Mistral-7B-v0.3
model_type: MistralForCausalLM
tokenizer_type: LlamaTokenizer
is_mistral_derived_model: true

load_in_8bit: false
load_in_4bit: false
strict: false

datasets:
  - path: ./data/trainset_zh-tw-wikipedia_semiconductor.json
    type: completion
dataset_prepared_path: ./data/last_run_prepared/mistral/7b-instruct-v0.3/trainset_zh-tw-wikipedia_semiconductor
val_set_size: 0.05
output_dir: ./exp/mistral/7b-instruct-v0.3/rag_cp_freeze-top25layers-lm_head-trainset_zh-tw-wikipedia_semiconductor

sequence_len: 8192
sample_packing: true
pad_to_sequence_len: true
eval_sample_packing: False

wandb_project:
wandb_entity:
wandb_watch:
wandb_run_id:
wandb_log_model:

gradient_accumulation_steps: 1
micro_batch_size: 2
num_epochs: 8
optimizer: paged_adamw_32bit
lr_scheduler: cosine
learning_rate: 0.0002

train_on_inputs: false
group_by_length: false
bf16: true
fp16: false
tf32: false

gradient_checkpointing: true
early_stopping_patience:
resume_from_checkpoint:
local_rank:
logging_steps: 10
xformers_attention:
flash_attention: true

warmup_steps: 10
eval_steps: 20
eval_table_size:
eval_table_max_new_tokens:
save_steps: 50
debug:
deepspeed:
weight_decay: 0.01
fsdp:
fsdp_config:
special_tokens:
  bos_token: "<s>"
  eos_token: "</s>"
  unk_token: "<unk>"

frozen_parameters:
  - ^lm_head.weight$
  - ^model.layers.0.self_attn.q_proj.weight$
  - ^model.layers.0.self_attn.k_proj.weight$
  - ^model.layers.0.self_attn.v_proj.weight$
  - ^model.layers.0.self_attn.o_proj.weight$
  - ^model.layers.0.mlp.gate_proj.weight$
  - ^model.layers.0.mlp.up_proj.weight$
  - ^model.layers.0.mlp.down_proj.weight$
  - ^model.layers.0.input_layernorm.weight$
  - ^model.layers.0.post_attention_layernorm.weight$
  - ^model.layers.1.self_attn.q_proj.weight$
  - ^model.layers.1.self_attn.k_proj.weight$
  - ^model.layers.1.self_attn.v_proj.weight$
  - ^model.layers.1.self_attn.o_proj.weight$
  - ^model.layers.1.mlp.gate_proj.weight$
  - ^model.layers.1.mlp.up_proj.weight$
  - ^model.layers.1.mlp.down_proj.weight$
  - ^model.layers.1.input_layernorm.weight$
  - ^model.layers.1.post_attention_layernorm.weight$
  - ^model.layers.2.self_attn.q_proj.weight$
  - ^model.layers.2.self_attn.k_proj.weight$
  - ^model.layers.2.self_attn.v_proj.weight$
  - ^model.layers.2.self_attn.o_proj.weight$
  - ^model.layers.2.mlp.gate_proj.weight$
  - ^model.layers.2.mlp.up_proj.weight$
  - ^model.layers.2.mlp.down_proj.weight$
  - ^model.layers.2.input_layernorm.weight$
  - ^model.layers.2.post_attention_layernorm.weight$
  - ^model.layers.3.self_attn.q_proj.weight$
  - ^model.layers.3.self_attn.k_proj.weight$
  - ^model.layers.3.self_attn.v_proj.weight$
  - ^model.layers.3.self_attn.o_proj.weight$
  - ^model.layers.3.mlp.gate_proj.weight$
  - ^model.layers.3.mlp.up_proj.weight$
  - ^model.layers.3.mlp.down_proj.weight$
  - ^model.layers.3.input_layernorm.weight$
  - ^model.layers.3.post_attention_layernorm.weight$
  - ^model.layers.4.self_attn.q_proj.weight$
  - ^model.layers.4.self_attn.k_proj.weight$
  - ^model.layers.4.self_attn.v_proj.weight$
  - ^model.layers.4.self_attn.o_proj.weight$
  - ^model.layers.4.mlp.gate_proj.weight$
  - ^model.layers.4.mlp.up_proj.weight$
  - ^model.layers.4.mlp.down_proj.weight$
  - ^model.layers.4.input_layernorm.weight$
  - ^model.layers.4.post_attention_layernorm.weight$
  - ^model.layers.5.self_attn.q_proj.weight$
  - ^model.layers.5.self_attn.k_proj.weight$
  - ^model.layers.5.self_attn.v_proj.weight$
  - ^model.layers.5.self_attn.o_proj.weight$
  - ^model.layers.5.mlp.gate_proj.weight$
  - ^model.layers.5.mlp.up_proj.weight$
  - ^model.layers.5.mlp.down_proj.weight$
  - ^model.layers.5.input_layernorm.weight$
  - ^model.layers.5.post_attention_layernorm.weight$
  - ^model.layers.6.self_attn.q_proj.weight$
  - ^model.layers.6.self_attn.k_proj.weight$
  - ^model.layers.6.self_attn.v_proj.weight$
  - ^model.layers.6.self_attn.o_proj.weight$
  - ^model.layers.6.mlp.gate_proj.weight$
  - ^model.layers.6.mlp.up_proj.weight$
  - ^model.layers.6.mlp.down_proj.weight$
  - ^model.layers.6.input_layernorm.weight$
  - ^model.layers.6.post_attention_layernorm.weight$
  - ^model.layers.7.self_attn.q_proj.weight$
  - ^model.layers.7.self_attn.k_proj.weight$
  - ^model.layers.7.self_attn.v_proj.weight$
  - ^model.layers.7.self_attn.o_proj.weight$
  - ^model.layers.7.mlp.gate_proj.weight$
  - ^model.layers.7.mlp.up_proj.weight$
  - ^model.layers.7.mlp.down_proj.weight$
  - ^model.layers.7.input_layernorm.weight$
  - ^model.layers.7.post_attention_layernorm.weight$
  - ^model.layers.8.self_attn.q_proj.weight$
  - ^model.layers.8.self_attn.k_proj.weight$
  - ^model.layers.8.self_attn.v_proj.weight$
  - ^model.layers.8.self_attn.o_proj.weight$
  - ^model.layers.8.mlp.gate_proj.weight$
  - ^model.layers.8.mlp.up_proj.weight$
  - ^model.layers.8.mlp.down_proj.weight$
  - ^model.layers.8.input_layernorm.weight$
  - ^model.layers.8.post_attention_layernorm.weight$
  - ^model.layers.9.self_attn.q_proj.weight$
  - ^model.layers.9.self_attn.k_proj.weight$
  - ^model.layers.9.self_attn.v_proj.weight$
  - ^model.layers.9.self_attn.o_proj.weight$
  - ^model.layers.9.mlp.gate_proj.weight$
  - ^model.layers.9.mlp.up_proj.weight$
  - ^model.layers.9.mlp.down_proj.weight$
  - ^model.layers.9.input_layernorm.weight$
  - ^model.layers.9.post_attention_layernorm.weight$
  - ^model.layers.9.self_attn.q_proj.weight$
  - ^model.layers.9.self_attn.k_proj.weight$
  - ^model.layers.9.self_attn.v_proj.weight$
  - ^model.layers.9.self_attn.o_proj.weight$
  - ^model.layers.9.mlp.gate_proj.weight$
  - ^model.layers.9.mlp.up_proj.weight$
  - ^model.layers.9.mlp.down_proj.weight$
  - ^model.layers.9.input_layernorm.weight$
  - ^model.layers.9.post_attention_layernorm.weight$
  - ^model.layers.10.self_attn.q_proj.weight$
  - ^model.layers.10.self_attn.k_proj.weight$
  - ^model.layers.10.self_attn.v_proj.weight$
  - ^model.layers.10.self_attn.o_proj.weight$
  - ^model.layers.10.mlp.gate_proj.weight$
  - ^model.layers.10.mlp.up_proj.weight$
  - ^model.layers.10.mlp.down_proj.weight$
  - ^model.layers.10.input_layernorm.weight$
  - ^model.layers.10.post_attention_layernorm.weight$
  - ^model.layers.11.self_attn.q_proj.weight$
  - ^model.layers.11.self_attn.k_proj.weight$
  - ^model.layers.11.self_attn.v_proj.weight$
  - ^model.layers.11.self_attn.o_proj.weight$
  - ^model.layers.11.mlp.gate_proj.weight$
  - ^model.layers.11.mlp.up_proj.weight$
  - ^model.layers.11.mlp.down_proj.weight$
  - ^model.layers.11.input_layernorm.weight$
  - ^model.layers.11.post_attention_layernorm.weight$
  - ^model.layers.12.self_attn.q_proj.weight$
  - ^model.layers.12.self_attn.k_proj.weight$
  - ^model.layers.12.self_attn.v_proj.weight$
  - ^model.layers.12.self_attn.o_proj.weight$
  - ^model.layers.12.mlp.gate_proj.weight$
  - ^model.layers.12.mlp.up_proj.weight$
  - ^model.layers.12.mlp.down_proj.weight$
  - ^model.layers.12.input_layernorm.weight$
  - ^model.layers.12.post_attention_layernorm.weight$
  - ^model.layers.13.self_attn.q_proj.weight$
  - ^model.layers.13.self_attn.k_proj.weight$
  - ^model.layers.13.self_attn.v_proj.weight$
  - ^model.layers.13.self_attn.o_proj.weight$
  - ^model.layers.13.mlp.gate_proj.weight$
  - ^model.layers.13.mlp.up_proj.weight$
  - ^model.layers.13.mlp.down_proj.weight$
  - ^model.layers.13.input_layernorm.weight$
  - ^model.layers.13.post_attention_layernorm.weight$
  - ^model.layers.14.self_attn.q_proj.weight$
  - ^model.layers.14.self_attn.k_proj.weight$
  - ^model.layers.14.self_attn.v_proj.weight$
  - ^model.layers.14.self_attn.o_proj.weight$
  - ^model.layers.14.mlp.gate_proj.weight$
  - ^model.layers.14.mlp.up_proj.weight$
  - ^model.layers.14.mlp.down_proj.weight$
  - ^model.layers.14.input_layernorm.weight$
  - ^model.layers.14.post_attention_layernorm.weight$
  - ^model.layers.15.self_attn.q_proj.weight$
  - ^model.layers.15.self_attn.k_proj.weight$
  - ^model.layers.15.self_attn.v_proj.weight$
  - ^model.layers.15.self_attn.o_proj.weight$
  - ^model.layers.15.mlp.gate_proj.weight$
  - ^model.layers.15.mlp.up_proj.weight$
  - ^model.layers.15.mlp.down_proj.weight$
  - ^model.layers.15.input_layernorm.weight$
  - ^model.layers.15.post_attention_layernorm.weight$
  - ^model.layers.16.self_attn.q_proj.weight$
  - ^model.layers.16.self_attn.k_proj.weight$
  - ^model.layers.16.self_attn.v_proj.weight$
  - ^model.layers.16.self_attn.o_proj.weight$
  - ^model.layers.16.mlp.gate_proj.weight$
  - ^model.layers.16.mlp.up_proj.weight$
  - ^model.layers.16.mlp.down_proj.weight$
  - ^model.layers.16.input_layernorm.weight$
  - ^model.layers.16.post_attention_layernorm.weight$
  - ^model.layers.17.self_attn.q_proj.weight$
  - ^model.layers.17.self_attn.k_proj.weight$
  - ^model.layers.17.self_attn.v_proj.weight$
  - ^model.layers.17.self_attn.o_proj.weight$
  - ^model.layers.17.mlp.gate_proj.weight$
  - ^model.layers.17.mlp.up_proj.weight$
  - ^model.layers.17.mlp.down_proj.weight$
  - ^model.layers.17.input_layernorm.weight$
  - ^model.layers.17.post_attention_layernorm.weight$
  - ^model.layers.18.self_attn.q_proj.weight$
  - ^model.layers.18.self_attn.k_proj.weight$
  - ^model.layers.18.self_attn.v_proj.weight$
  - ^model.layers.18.self_attn.o_proj.weight$
  - ^model.layers.18.mlp.gate_proj.weight$
  - ^model.layers.18.mlp.up_proj.weight$
  - ^model.layers.18.mlp.down_proj.weight$
  - ^model.layers.18.input_layernorm.weight$
  - ^model.layers.18.post_attention_layernorm.weight$
  - ^model.layers.19.self_attn.q_proj.weight$
  - ^model.layers.19.self_attn.k_proj.weight$
  - ^model.layers.19.self_attn.v_proj.weight$
  - ^model.layers.19.self_attn.o_proj.weight$
  - ^model.layers.19.mlp.gate_proj.weight$
  - ^model.layers.19.mlp.up_proj.weight$
  - ^model.layers.19.mlp.down_proj.weight$
  - ^model.layers.19.input_layernorm.weight$
  - ^model.layers.19.post_attention_layernorm.weight$
  - ^model.layers.20.self_attn.q_proj.weight$
  - ^model.layers.20.self_attn.k_proj.weight$
  - ^model.layers.20.self_attn.v_proj.weight$
  - ^model.layers.20.self_attn.o_proj.weight$
  - ^model.layers.20.mlp.gate_proj.weight$
  - ^model.layers.20.mlp.up_proj.weight$
  - ^model.layers.20.mlp.down_proj.weight$
  - ^model.layers.20.input_layernorm.weight$
  - ^model.layers.20.post_attention_layernorm.weight$
  - ^model.layers.21.self_attn.q_proj.weight$
  - ^model.layers.21.self_attn.k_proj.weight$
  - ^model.layers.21.self_attn.v_proj.weight$
  - ^model.layers.21.self_attn.o_proj.weight$
  - ^model.layers.21.mlp.gate_proj.weight$
  - ^model.layers.21.mlp.up_proj.weight$
  - ^model.layers.21.mlp.down_proj.weight$
  - ^model.layers.21.input_layernorm.weight$
  - ^model.layers.21.post_attention_layernorm.weight$
  - ^model.layers.22.self_attn.q_proj.weight$
  - ^model.layers.22.self_attn.k_proj.weight$
  - ^model.layers.22.self_attn.v_proj.weight$
  - ^model.layers.22.self_attn.o_proj.weight$
  - ^model.layers.22.mlp.gate_proj.weight$
  - ^model.layers.22.mlp.up_proj.weight$
  - ^model.layers.22.mlp.down_proj.weight$
  - ^model.layers.22.input_layernorm.weight$
  - ^model.layers.22.post_attention_layernorm.weight$
  - ^model.layers.23.self_attn.q_proj.weight$
  - ^model.layers.23.self_attn.k_proj.weight$
  - ^model.layers.23.self_attn.v_proj.weight$
  - ^model.layers.23.self_attn.o_proj.weight$
  - ^model.layers.23.mlp.gate_proj.weight$
  - ^model.layers.23.mlp.up_proj.weight$
  - ^model.layers.23.mlp.down_proj.weight$
  - ^model.layers.23.input_layernorm.weight$
  - ^model.layers.23.post_attention_layernorm.weight$
  - ^model.layers.24.self_attn.q_proj.weight$
  - ^model.layers.24.self_attn.k_proj.weight$
  - ^model.layers.24.self_attn.v_proj.weight$
  - ^model.layers.24.self_attn.o_proj.weight$
  - ^model.layers.24.mlp.gate_proj.weight$
  - ^model.layers.24.mlp.up_proj.weight$
  - ^model.layers.24.mlp.down_proj.weight$
  - ^model.layers.24.input_layernorm.weight$
  - ^model.layers.24.post_attention_layernorm.weight$
